grafana:
  enabled: true

  service:
    type: ClusterIP

  persistence:
    enabled: true
    size: 5Gi
    storageClassName: gp2

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1.5Gi

alertmanager:
  alertmanagerSpec:
    replicas: 1

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

defaultRules:
  create: true

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
